server:
  port: 8080
  servlet:
    context-path: /demo
qiniu:
  ## 此处填写你自己的七牛云 access key
  accessKey: ioNGrw3wA2u16kzwaaaBv73jOTeAEmovlEDll0Qn
  ## 此处填写你自己的七牛云 secret key
  secretKey: gmyHNP_GgCocsvn3MhNi5Z_yVHecL02yf6tlWlLd
  ## 此处填写你自己的七牛云 bucket
  bucket: sloop-pub
  ## 此处填写你自己的七牛云 域名
  prefix: sloop-pub.s3-cn-east-1.qiniucs.com
spring:
  servlet:
    multipart:
      enabled: true
      location: D:/code/spring-boot-demo/spring-boot-demo-upload/temp
      file-size-threshold: 5MB
      max-file-size: 20MB